version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: D4le713gw
      MYSQL_DATABASE: wp-sait-vaddeil
      MYSQL_USER: vaddeil
      MYSQL_PASSWORD: D4le713gw
    networks:
      - back

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes:
      - ./app/public/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: vaddeil
      WORDPRESS_DB_PASSWORD: D4le713gw
      WORDPRESS_DB_NAME: wp-sait-vaddeil
    ports:
      - 80:80
      - 443:443
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: D4le713gw
    networks:
      - back

networks:
  back:
volumes:
  db_data: {}
